
Loading Libraries
```{r}
library(dplyr)
library(corrplot)
library(igraph)
library(infotheo)
source("./functions.R")
```


```{r}
log_transform <- F
mutual_info <- T

for (dir. in list.dirs("../../data/")){
  if (grepl("denovo$", dir.) || grepl("REFs$", dir.)){
    ### Entering potato_denovo expression files (Universidad Nacional)
    if (grepl("denovo$", dir.)){
      print(dir.)
      for (file. in list.files(dir.)){
        if (grepl("^A_TPM", file.)){
          print(file.)
          de.novo.table <- read.delim(paste0(dir.,"/", file.), sep="\t", header=TRUE, na.strings="") %>% select("Row.Labels", starts_with("A")) 
          
          # ====================== Loading gene names of interest  ================================================
          # --Load genes from Falvonoids path
          message("Loading Anthocyanin annotated  HOGS...")
          floavonoid.path.HOGS <- read.csv("../../results/filtered_genes/flav.HOGS.csv")$`annot.info` %>% as.vector()
          print(cat("Number of unique Anthocyanin annotated HOG HOGS is ==>", length(floavonoid.path.HOGS)))

          # --Load most variable HOGS
          message("Loading most variable HOGS...")
          most.var.HOGS.names <- read.csv("../../results/filtered_genes/6000_most_variable_genes.csv6000.csv")$`Var1` %>% as.vector()
          
          # --Load DEHS (differentially expressed HOGS)
          message("Loading differentially expressed HOGS...")
          D.E.HOGS <- c()
          DEHs.Cyanidin <-  read.csv("../../results/DEGS/DEGS_denovo/model/Cyanidin.csv")$`total.DEH` %>% as.vector() 
          DEHs.Delphinidin <-  read.csv("../../results/DEGS/DEGS_denovo/model/Delphinidin.csv")$`total.DEH` %>% as.vector()
          DEHs.Peonidin <-  read.csv("../../results/DEGS/DEGS_denovo/model/Peonidin.csv")$`total.DEH` %>% as.vector()
          DEHs.Petunidin <-  read.csv("../../results/DEGS/DEGS_denovo/model/Petunidin.csv")$`total.DEH` %>% as.vector()
          DEHs.Pelargonidin <-  read.csv("../../results/DEGS/DEGS_denovo/model/Pelargonidin.csv")$`total.DEH` %>% as.vector()
          
          #Create vector with all DEHs names
          D.E.HOGS <- c(D.E.HOGS, DEHs.Cyanidin, DEHs.Delphinidin, DEHs.Peonidin, DEHs.Petunidin, DEHs.Pelargonidin)
          D.E.HOGS <- names(table(D.E.HOGS)) #Define unique HOGS
          message(cat("Number of unique differentially expressed HOGS is ==>", length(D.E.HOGS)))
    
          
          # =========================== Obtaining expression matrix for all genes of interest ============================
          #===============================================================================================================
          
          network.genes <- c(D.E.HOGS, floavonoid.path.HOGS) # --> Enter here as a vector all genes loaded from previous step
          
          if (log_transform){
            message("Obtaining log 2 expression matrix for all genes of interest...")
            expression.data <- get.filtered.matrix(names(table(network.genes)), de.novo.table)
            hog.names <- expression.data$Row.Labels
            rownames(expression.data) <- hog.names #Rename expression data with gene names
            expression.data <- expression.data %>% select(-Row.Labels) %>% log(base = 2)
            expression.data <-  data.frame(lapply(expression.data, function(x) ifelse(x == -Inf, 0, x)))
            rownames(expression.data) <- hog.names
            print(cat("Filtered dataframe dimenstions are --> ", dim(expression.data)))
          } 
          
          else {
            message("Obtaining raw expression matrix for all genes of interest...")
            expression.data <- get.filtered.matrix(names(table(network.genes)), de.novo.table)
            rownames(expression.data) <- expression.data$Row.Labels #Rename expression data with gene names
            expression.data <- expression.data %>% select(-Row.Labels)
            print(cat("Filtered dataframe dimenstions are --> ", dim(expression.data)))
          }

          # ====================== Obtaining similarity matrix for all genes of interest ==========================
          #========================================================================================================
          if (mutual_info){
            # --Obtaining mutual information
            message("Obtaining mututal information for all genes of interest...")
            discretized.matrix <-discretize(t(expression.data), disc = "equalfreq", nbins = ceiling(1+log(ncol(expression.data))))
            sim.matrix <- mutinformation(discretized.matrix, method = "emp")
            
            #Rename correlation matrix with HOGS names
            colnames(sim.matrix) <- rownames(expression.data)
            rownames(sim.matrix) <- rownames(expression.data)
            
            View(sim.matrix)
            # S1 <- sqrt(1/exp(-2*sim.matrix))
            # S1[which(is.na(S1))] <- 0
            # hist(S1, xlim=c(0,1))
            
            
          } else if (!mutual_info){
            # --Obtaining correlation matrix for all genes
            message("Obtaining correlation matrix for all genes of interest...")
            sim.matrix <- abs(cor(t(expression.data), use = "pairwise.complete.obs"))
            #Rename correlation matrix with HOGS names
            colnames(sim.matrix) <- rownames(expression.data)
            rownames(sim.matrix) <- rownames(expression.data)
            # stop("Checking corr matrix")
          }
          
          # ====================== Check point for correlated genes ==========================
          # --Filtering out low correlated genes
          # High.corr.genes <- get.highCorr.genes(cor.matrix = cor.matrix, threshold = 0.5)
          # stop("Stopping code for mantenaince")

          # ===================== Determining the best threshold to work with on getting the network =============
          message("Getting clustering coefficients...")
          # net.coefficients <- get.network.coefficients(cor.matrix) #Get clustering coefficients
          # stop("Stop for mantainence")
          
          n <- nrow(sim.matrix)
          C <- matrix(nrow = n, ncol = 100)
          K <- matrix(nrow=n, ncol=100)
          ltaos <- seq(0.01,0.99,by=0.01)
          
          for(tao in ltaos){
            print(tao)
            ##Matriz de adyacencia:
            A=matrix(0,nrow=n,ncol=n)    
            ##Completa la matriz de adyacencia usando la funci?n de adyacencia:
            for(i in 1:n){  
              A[which(sim.matrix[,i]>=tao),i]<-1
              A[which(sim.matrix[,i]<tao),i]<-0
            }
            ##Transforma la matriz A en un objeto igraph:
            A=graph.adjacency(A,mode="undirected",diag=FALSE)
            ##Calcula el Ci de los nodos:
            Cv=transitivity(A,type="local")
            ##Calcula el ki de los nodos:
            Kv=degree(A,loops=FALSE)
            ##Guarda Ci y ki en los vectores C y K respectivamente:
            K[,round(tao*100,0)]<-Kv
            C[,round(tao*100,0)]<-Cv
          }
          
          Cr=Co=rep(0,100)
          ##Para cada valor de tao:
          for(i in round(ltaos*100,0))
            {  
            gn<-which(K[,i]>=1)#Posici?n de los genes conectados en la red
            kn=length(gn)#N?mero de nodos en la red
            k1=1/kn*sum(K[gn,i])#Variable en ecuaci?n 3 (Ver Elo et.al. 2007)
            k2=1/kn*sum(K[gn,i]^2)#Variable en ecuaci?n 3 (Ver Elo et.al. 2007)
            Co[i]=((k2-k1)^2)/(kn*k1^3) #Coeficiente de agrupamiento esperado para una red aleatoria
            if(kn==0){Co[i]=0}#Si no hay nodos conectados: Co=0
            gn<-which(K[,i]>1)#Posici?n de los genes con k1>1.
            kn=length(gn)#N?mero de genes con m?s de una arista en la red
            Cr[i]=1/kn*sum(C[gn,i])#Coeficiente de agrupamiento observado en la red.
            if(kn==0){Cr[i]=0}#Si no hay nodos conectados: Cr=0
          }
         
         # hist(K[,99],xlab = "Degree", main = "Threshold 0.99") ##### Plot de grado
         # plot(ltaos,abs(Cr-Co)[ltaos*100],t="l",xlab="Threshold",ylab="|C-Co|")
         
         stop("Determine TAO value")
         dif=runmed(abs(Cr-Co),k=3,endrule="constant")[1:100]
         plot(ltaos,dif[ltaos*100],t="l",xlab="Threshold",ylab="|C-Co|")
         identify(ltaos,dif[ltaos*100],n=1) / 100

        }
      }
    }
  }
}
```





```{r}
## ========================================CREATE NETWORK
TAO <- 0.71


for (tao in TAO){
  #Define matriz de adyacencia:
  A=matrix(0,nrow=n,ncol=n)   

  #Completa la matriz de adyacencia usando la función de adyacencia:
  for(i in 1:n)
  {  
    A[which(sim.matrix[,i]>=tao),i]<-1
    A[which(sim.matrix[,i]<tao),i]<-0
  }
  
    #Trabajando con los nombres de los genes
    colnames(A) <- rownames(A) <- rownames(sim.matrix)
    
    #Convierte la diagonal en ceros (red no dirigida):
    diag(A)<-0
    
    #Elimina nodos no conectados:
    A=A[which(K[,round(tao*100,0)]>0),which(K[,round(tao*100,0)]>0)]

    class(A)
    dim(A)
    
    A=graph.adjacency(A,mode="undirected",add.colnames=NULL,diag=FALSE)
    plot(A)
    
    vertex_colors <- rep("lightblue", 1181)
    vertex_colors[1:924] <- "red"

    plot.igraph(A,layout=layout_with_kk,vertex.color = vertex_colors,vertex.size=5,edge.color="darkgreen",vertex.label.font=1,vertex.label.cex=0.6, height=800, width=800, rescale = T)
    
     ## ========================================================== NETWORK ANALYSIS ======================================================
     ## ==================================================================================================================================
    red_info <- list()
   
    #========================================================== LOG TRANSFORMED ============================================================
    if (log_transform){
          
    #save graph object in the list info
    red_info[["log"]][[as.character(tao)]][["A"]] <- A
    
    #Número de nodos
    red_info[["log"]][[as.character(tao)]][["Length"]] <-  length(V(A))
    
    #=============================GET CLUSTERS ==============================
    red_info[["log"]][[as.character(tao)]][["Clusters"]] <- clusters(A, mode=c("weak"))
    # ======== Save them ========
    if (!mutual_info){
        saving.dir <- sprintf("../../results/networks/small/log_transformed/corr/%s/clusters/", tao)
        tryCatch({write.csv(data.frame(red_info[["log"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))},
                 error = function(e) {create.dir(saving.dir)
                   write.csv(data.frame(red_info[["log"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))})
        
      } else if (mutual_info){
        saving.dir <- sprintf("../../results/networks/small/log_transformed/mutual_info/%s/clusters/", tao)
        tryCatch({write.csv(data.frame(red_info[["log"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))},
                 error = function(e) {create.dir(saving.dir)
                   write.csv(data.frame(red_info[["log"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))})
      }
      
      
      #Tamaño de clusters
      red_info[["log"]][[as.character(tao)]][["Clusters size"]] <- clusters(A, mode=c("weak"))$csize
      
      #Transitividad
      red_info[["log"]][[as.character(tao)]][["Transitividad"]] <- transitivity(A, type="global") 
      
      #Diámetro
      red_info[["log"]][[as.character(tao)]][["Diameter"]] <- diameter(A)
      
    
      
       #============= SAVE GRAPH
        if (mutual_info){
          saving.dir <- sprintf("../../results/networks/small/log_transformed/mutual_info/%s/graph/", tao)
          tryCatch({write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")},
               error = function(e) {create.dir(saving.dir)
                 write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")})
          
        } else if (!mutual_info) {
           saving.dir <- sprintf("../../results/networks/small/log_transformed/corr/%s/graph/", tao)
          tryCatch({write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")},
               error = function(e) {create.dir(saving.dir)
                 write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")})
        }
        
        #============= DEGREE
        deg <- degree(A, mode="all")
        red_info[["log"]][[as.character(tao)]][["Degree"]] <- deg
        #Guarda tabla con información de grado
        degree.table <- data.frame(Degree = red_info[["log"]][[as.character(tao)]][["Degree"]])
        
        if (mutual_info){
          saving.dir <- sprintf("../../results/networks/small/log_transformed/mutual_info/%s/degree/", tao)
          tryCatch({write.csv(degree.table, paste0(saving.dir, "degree.csv"))},
               error = function(e) {create.dir(saving.dir)
                 write.csv(degree.table, paste0(saving.dir, "degree.csv"))})
           
           
        } else if (!mutual_info){
          saving.dir <- sprintf("../../results/networks/small/log_transformed/corr/%s/degree/", tao)
          tryCatch({write.csv(degree.table, paste0(saving.dir, "degree.csv"))},
               error = function(e) {create.dir(saving.dir)
                 write.csv(degree.table, paste0(saving.dir, "degree.csv"))})
        }
      #========================================================== NO LOG TRANSFORMED ==========================================================
    } else if(!log_transform) { 
      
      #save graph object in the list info
    red_info[["raw"]][[as.character(tao)]][["A"]] <- A
    
    #Número de nodos
    red_info[["raw"]][[as.character(tao)]][["Length"]] <-  length(V(A))
    
    #=============================GET CLUSTERS ==============================
    red_info[["raw"]][[as.character(tao)]][["Clusters"]] <- clusters(A, mode=c("weak"))
    # ======== Save them ========
    if (!mutual_info){
        saving.dir <- sprintf("../../results/networks/small/raw/corr/%s/clusters/", tao)
        tryCatch({write.csv(data.frame(red_info[["raw"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))},
                 error = function(e) {create.dir(saving.dir)
                   write.csv(data.frame(red_info[["raw"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))})
        
      } else if (mutual_info){
        saving.dir <- sprintf("../../results/networks/small/raw/mutual_info/%s/clusters", tao)
        tryCatch({write.csv(data.frame(red_info[["raw"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))},
                 error = function(e) {create.dir(saving.dir)
                   write.csv(data.frame(red_info[["raw"]][[as.character(tao)]][["Clusters"]]$membership), paste0(saving.dir,"clusters.csv"))})
      }
      
      
      #Tamaño de clusters
      red_info[["raw"]][[as.character(tao)]][["Clusters size"]] <- clusters(A, mode=c("weak"))$csize
      
      #Transitividad
      red_info[["raw"]][[as.character(tao)]][["Transitividad"]] <- transitivity(A, type="global") 
      
      #Diámetro
      red_info[["raw"]][[as.character(tao)]][["Diameter"]] <- diameter(A)
      
      #============= SAVE GRAPH
        if (mutual_info){
          saving.dir <- sprintf("../../results/networks/small/raw/mutual_info/%s/graph/", tao)
          tryCatch({write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")},
               error = function(e) {create.dir(saving.dir)
                 write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")})
          
        } else if (!mutual_info) {
           saving.dir <- sprintf("../../results/networks/small/raw/corr/%s/graph/", tao)
          tryCatch({write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")},
               error = function(e) {create.dir(saving.dir)
                 write.graph(A, paste0(saving.dir, "graph.txt"),format="ncol")})
        }
        
        #============= DEGREE
        deg <- degree(A, mode="all")
        red_info[["log"]][[as.character(tao)]][["Degree"]] <- deg
        #Guarda tabla con información de grado
        degree.table <- data.frame(Degree = red_info[["log"]][[as.character(tao)]][["Degree"]])
        
        if (mutual_info){
          saving.dir <- sprintf("../../results/networks/small/raw/mutual_info/%s/degree/", tao)
          tryCatch({write.csv(degree.table, paste0(saving.dir, "degree.csv"))},
               error = function(e) {create.dir(saving.dir)
                 write.csv(degree.table, paste0(saving.dir, "degree.csv"))})
           
           
        } else if (!mutual_info){
          saving.dir <- sprintf("../../results/networks/small/raw/corr/%s/degree/", tao)
          tryCatch({write.csv(degree.table, paste0(saving.dir, "degree.csv"))},
               error = function(e) {create.dir(saving.dir)
                 write.csv(degree.table, paste0(saving.dir, "degree.csv"))})
        }
    }
    #============================================================================================================================
    
    barplot(table(deg),las=2)
    plot(A, vertex.size=deg)
    plot.igraph(A,layout=layout_with_kk,vertex.color = 'lightblue',vertex.size=deg,edge.color="darkgreen",vertex.label.font=1,vertex.label.cex=0.6 )
    
    hist(deg, breaks=1:vcount(A)-1, main="Histogram of node degree")
    
    
    deg.dist <- degree_distribution(A, cumulative=T, mode="all")
    plot( x=0:max(deg), y=1-deg.dist, pch=19, cex=1.2, col="orange", 
          xlab="Degree", ylab="Cumulative Frequency")
    
    #Guarda información de centralización
    red_info[[as.character(tao)]][["centr_degree"]] <- centr_degree(A, mode="in", normalized=T)
    # cd<-centr_degree(A, mode="in", normalized=T)
    # cd$centralization
    # cd$res
    
    #Eigen centrality
    red_info[[as.character(tao)]][["eigen_centrality"]] <- eigen_centrality(A, directed=F, weights=NA)
    # eigc<-eigen_centrality(A, directed=F, weights=NA)
    
    #Hub score
    red_info[[as.character(tao)]][["hub_score"]] <- hub_score(A, weights=NA)$vector
    # hs <- hub_score(A, weights=NA)$vector
    # hs
    # sort(hs,decreasing = TRUE)
    # sort(deg,decreasing = TRUE)
}



```




