
```{r}
library(dplyr)
```

Functions
```{r}
rowVarCoef <- function(x)
{
  rowSds(x) / rowMeans(x)
}
```

Extract the 6000 most variable genes from the HOGS expression data and save them
```{r}
for (dir. in list.dirs("../../data/")){
  if (grepl("denovo$", dir.) || grepl("REFs$", dir.)){
    ### Entering potato_denovo expression files (Universidad Nacional)
    if (grepl("denovo$", dir.)){
      print(dir.)
      for (file. in list.files(dir.)){
        print(file.)
        if (grepl("^A_TPM", file.)){
          de.novo.table <- read.delim(paste0(dir.,"/", file.), sep="\t", header=TRUE, na.strings="") %>% dplyr::select("Row.Labels", starts_with("A")) 
          # ====================== Filtering Data  ==================================
          # -- Expression = 0
          de.novo.table <- de.novo.table[rowSums(as.matrix(de.novo.table[2:dim(de.novo.table)[2]])) != 0,]
          print(dim(de.novo.table))
          
          # -- Expression >= 5000
          de.novo.table <- de.novo.table[5e3 > apply(de.novo.table[2:dim(de.novo.table)[2]], 1, max),]
          
          # ====================== Getting variation coefficient ====================
          de.novo.table <- de.novo.table %>% mutate(vCoef = rowVarCoef(as.matrix(across(c(starts_with("A")))))) %>% arrange(desc(vCoef))
          # View(de.novo.table)
          
          # --Save  most variable genes
          saving.dir <- "../../results/filtered_genes/"
          if (!file.exists(saving.dir)){
            dir.create(saving.dir)
          }
          #write.csv(data.frame(table(de.novo.table$Row.Labels[1:6000])), paste0(saving.dir,"6000.csv"))
          
          # -- Save 10% and 15% of most variable genes
          percentage.float <- 0.15
          
          saving.dir <- "../../results/filtered_genes/"
          if (!file.exists(saving.dir)){
            dir.create(saving.dir)
          }
          percentage.value <- ceiling(dim(de.novo.table)[1] * percentage.float)
          print(percentage.value)
          write.csv(data.frame(table(de.novo.table$Row.Labels[1:percentage.value])), paste0(saving.dir, sprintf("%s_most_variable_genes.csv", percentage.float)))
          
          
          
          
        }
      }
    }
  }
}
```

