---
title: "R Notebook"
output: html_notebook
---

```{r}
library(pheatmap)
require(DESeq2)
library(lattice)
library(Matrix)
library(genefilter)
library(gcrma)
library(corrplot)
require(ggplot2)
library(apeglm)
library(tidyr)
library(vsn)
library(dplyr)
```

```{r}
source("./functions_preprocessing.R")
source("./functions_diffExp.R")
```

```{r}
SHRINKAGE <- T

for (dir. in list.dirs("../../data/")){
  if (grepl("denovo$", dir.) || grepl("REFs$", dir.)){
    ### Entering potato_denovo expression files (Universidad Nacional)
    if (grepl("denovo$", dir.)){
      message("Working with denovo dataset A counts")
      print(dir.)
      for (file. in list.files(dir.)){
        #print(file.)
        if (grepl("^A_TPM", file.)){
          #Access to counts A file
          print(file.)
          # ==================== Accessing expression data
          de.novo.table <- read.delim(paste0(dir.,"/", file.), sep="\t", header=TRUE, na.strings="") %>% select("Row.Labels", starts_with("A")) 
          
          # ==================== Rename columns
          colnames(de.novo.table) <- c("Row.Labels", substr(colnames(de.novo.table[2:dim(de.novo.table)[2]]), 3,  8))
          print(cat("Dimensions of expression file are = ",dim(de.novo.table)))
          
          # ==================== Convert to integer type each column
          for (column in colnames(de.novo.table[2:dim(de.novo.table)[2]])){
            de.novo.table[[column]] <- as.integer(round(de.novo.table[[column]]))
          } 
          # ================================ FILTERING DATA  =====================================
          message("Filtering expression data...")
          # ================================ Expression = 0
          de.novo.table <- de.novo.table[rowSums(as.matrix(de.novo.table[2:dim(de.novo.table)[2]])) != 0,]
          print(cat("Dimensions of expression file after expression = 0 filter are =", dim(de.novo.table)))
          
          # ================================ Variation = 0
          de.novo.table <- de.novo.table[0 < apply(de.novo.table[2:dim(de.novo.table)[2]], 1, var), ]
          print(cat("Dimensions of expression file after expression = 0 filter are =", dim(de.novo.table)))
          
          # =============================== DIFFERENTIAL EXPRESSION  ==============================
          message("Determining differential expression for all conditions...")
          
          # ============================== 1.Loading data for de novo dataset accesions
          accesions.info <- read.csv("../../data/potato_denovo/accesiones.csv")
          ## Define anthocyanin names
          anthocyanin.names <- c("Delphinidin","Peonidin","Cyanidin","Total.anthocyanins")
        
          ## Get accesion names present in expression data
          accesion_names <- names(de.novo.table)[2:dim(de.novo.table)[2]]
          ## Define quantiles to work on
          quantiles <- seq(30,60,5)
          #quantiles <- seq(30,60,30)
          ## Define group of accesions based on level of each anthocyanin (funcion return list)
          accesions.by.anthocyanin <- get.accessions.by.quantile(anthocyanins.vector=anthocyanin.names,
                                                                 accesions.dataset=accesions.info,
                                                                 accessions.vector=accesion_names, 
                                                                 quantiles.vector=quantiles)
          
          for (a in names(accesions.by.anthocyanin)){
            total.DEH <- c()
            message(sprintf("GETTING DEGs FOR CONTRASTS FOR %s", a))
            for (q in quantiles){
              message(sprintf("Including QUANTILE %s for contrast", q))
              below_quantile <- accesions.by.anthocyanin[[a]][[q]][["low.ammount"]]
              print(sprintf("Below quantile length--> %s", length(below_quantile)))
              above_quantile <- accesions.by.anthocyanin[[a]][[q]][["high.ammount"]]
              print(sprintf("Above quantile length --> %s", length(above_quantile)))
              
              accessions.contrast <- c(below_quantile,above_quantile)
              
              # =========================== Create the clade vector
              clade.vector <- get.clade.vector(dataset = accesions.info,
                                               contrast = accessions.contrast,
                                               mode = "clade")
              
              
              
              # =========================== Create contrast factor
              contrast.vector <- get.contrast.vector(accessions.contrast,
                                                     below_quantile = below_quantile,
                                                     above_quantile = above_quantile)
              print(contrast.vector)
              
              # =========================== Create coldata
              colData. <- data.frame(contrast=as.factor(contrast.vector), clado=as.factor(clade.vector))
              
              
              # =========================== Rearrange expression dataframe
              expression.data <- de.novo.table[, c("Row.Labels", below_quantile, above_quantile)]
              # =========================== Create Deseq2 object
              dds0 <- DESeq2::DESeqDataSetFromMatrix(countData = expression.data[2:dim(expression.data)[2]],
                                                     colData = colData.,
                                                     design = ~contrast+clado
              )
              dds0 <- DESeq2::estimateSizeFactors(dds0)
              out.factors <- names(sizeFactors(dds0)[sizeFactors(dds0) < 0.3 | sizeFactors(dds0) > 3])
              message(cat("Outstimated factors are ==> ", out.factors))
              
              
              if (is.null(out.factors)){
                message("No accession was removed after SizeFactors calculation")
                dds0 <- DESeq2::DESeq(dds0, test = "LRT", reduced = ~1)
                res0 <- results(dds0)
                resultsNames(dds0)
                # plotDispEsts(dds0)
                
                if (isTRUE(SHRINKAGE)){
                  message("Applying shrinkage method to fitted model")
                  resLFC0 <- lfcShrink(dds0, type = "apeglm")
                  #Get p values with Shrinkage
                  Padj0 <- data.frame(p=res0$padj[resLFC0$padj<0.95])
                  ggplot(Padj0, aes(x=p)) + geom_histogram(breaks = seq(0,0.95,0.05)) +
                    labs(y='frecuencia') + scale_x_continuous(breaks = seq(0,0.95,0.05))
                  
                  DEH <- de.novo.table[replace_na(resLFC0$padj <= 0.05, F), "Row.Labels"]  #Get differetentially expressed HOGS names
                  sprintf("DEH for quantile %d and Anthocyanin %s =", q, paste(DEH, collapse = ","))
                  total.DEH <- c(total.DEH, DEH)
                  
                } else {
                  # Get p values
                  Padj0 <- data.frame(p=res0$padj[res0$padj<0.95])
                  ggplot(Padj0, aes(x=p)) + geom_histogram(breaks = seq(0,0.95,0.05)) +
                    labs(y='frecuencia') + scale_x_continuous(breaks = seq(0,0.95,0.05))
                  
                  DEH <- de.novo.table[replace_na(res0$padj <= 0.05, F), "Row.Labels"]  #Get differetentially expressed HOGS names
                  sprintf("DEH for quantile %d and Anthocyanin %s =", q, paste(DEH, collapse = ","))
                  total.DEH <- c(total.DEH, DEH)
                }
                
              } else {
                print(sprintf("Removing %s from expression data after Size factors calculation", out.factors))
                #plotMA(resLFC0)
                dds0 <- dds0[, !colnames(dds0) %in% out.factors]
                message(sprintf("New Deseq object dimensions are ==> %s", paste(dim(dds0), collapse = ",")))
                dds0 <- DESeq(dds0, test="LRT", reduced=~1) #prueba de verosimilitud compara ajuste actual vs modelo nulo
                #dds0 <- DESeq(dds0, test="Wald")#prueba de Wald solo para dos condiciones
                res0 <- results(dds0)
                resultsNames(dds0) 
                #plotDispEsts(dds0) # estimaciones dispersiones  
                #plotMA(dds0)
                  
                if (isTRUE(SHRINKAGE)){
                  resLFC0 <- lfcShrink(dds0, type = "apeglm")
                  #Get p values with Shrinkage
                  Padj0 <- data.frame(p=res0$padj[resLFC0$padj<0.95])
                  ggplot(Padj0, aes(x=p)) + geom_histogram(breaks = seq(0,0.95,0.05)) +
                    labs(y='frecuencia') + scale_x_continuous(breaks = seq(0,0.95,0.05))
                  
                  DEH <- de.novo.table[replace_na(resLFC0$padj <= 0.05, F), "Row.Labels"]  #Get differetentially expressed HOGS names
                  sprintf("DEH for quantile %d and Anthocyanin %s =", q, paste(DEH, collapse = ","))
                  total.DEH <- c(total.DEH, DEH)
                  
                } else {
                  # Get p values
                  Padj0 <- data.frame(p=res0$padj[res0$padj<0.95])
                  ggplot(Padj0, aes(x=p)) + geom_histogram(breaks = seq(0,0.95,0.05)) +
                    labs(y='frecuencia') + scale_x_continuous(breaks = seq(0,0.95,0.05))
                  
                  DEH <- de.novo.table[replace_na(res0$padj <= 0.05, F), "Row.Labels"]  #Get differetentially expressed HOGS names
                  sprintf("DEH for quantile %d and Anthocyanin %s =", q, paste(DEH, collapse = ","))
                  total.DEH <- c(total.DEH, DEH)
                }
              }
            }
            DEHs.dataframe <- data.frame(table(total.DEH))
            write.csv(DEHs.dataframe, sprintf("../../results/DEGS/DEGS_denovo/%s.csv", a))
            }
          } 
        }
      
      
      } 
  #   else if (grepl("REFs_$", dir.)){
  #   ### Entering potato_denovo expression files
  #   print(dir.)
  #   for (file. in list.files(dir.)){
  #     #print(file.)
  #     if (grepl("^A_Potato", file.)){
  #       print(file.)
  #       #accessing expression data
  #       de_novo_table <- read.table(paste0(dir.,"/", file.), sep ="\t", header = TRUE, na.strings="")
  #       View(de_novo_table)
  #     } else if (grepl("^Annot", file.)){
  #       print(file.)
  #       #accessing annotation file
  #       REFs_table <- read.delim(paste0(dir.,"/", file.), sep="\t", header=TRUE, na.strings="")
  #       View(REFs_table)
  #       
  #     }
  #   }
  # }
  }
}
```

```{r}
View(colData.)
```
